apiVersion: v2
name: prometheus
description: A Helm chart for Kubernetes
version: 0.1.0
dependencies:
  - name: prometheus
    version: 15.14.x
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 6.40.x
    repository: https://grafana.github.io/helm-charts
