---
app: demo-app-python
image: "ghcr.io/kostya2011/python-logs-demo-app:b56e6990629bbeb76f3ff8e06879c01b58b60d2e-9245190938" # yamllint disable-line rule:line-length
type: python

container_ports: []
service_ports: []

resources:
  requests:
    memory: "128Mi"
    cpu: "64m"
  limits:
    memory: "128Mi"

monitoring:
  enabled: true
  metrics_path: "/metrics"
  metrics_port_number: 5000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

env: []
dns:
  config: {}
  policy: ""
affinity: {}
tolerations: {}
labels: {}
annotations: {}
priorityClassName: ""

check_recommended: true

pdb: {}

gh_packages_token: ""
