---
prometheus:
  rbac:
    create: true
  server:
    # Run prometheus in a single node mode
    replicaCount: 1
    extraFlags:
      - web.enable-lifecycle
      - web.enable-admin-api
      - storage.tsdb.wal-compression
    # PV config
    persistentVolume:
      enabled: true
      accessModes:
        - ReadWriteOnce
      # Additinal labels
      labels:
        environment: infrastructure
        app: prometheus
      annotations: {}
      existingClaim: ""
      mountPath: /data
      # Decrease default disk size
      size: 2Gi
    podLabels:
      environment: infrastructure
      app: prometheus
    # Decrease default limits
    resources:
      limits:
        cpu: 256m
        memory: 256Mi
      requests:
        cpu: 256m
        memory: 256Mi
    # https://github.com/prometheus-community/helm-charts/issues/2420
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
      runAsGroup: 0
      fsGroup: 0
  # Disable push-gateway and alertmanager
  pushgateway:
    enabled: false
  alertmanager:
    enabled: false

grafana:
  # Configure grafana datasources through values
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-server.demo-monitoring.svc.cluster.local # yamllint disable-line rule:line-length
