---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "py_log_demo.labels" . | indent 4 }}
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
{{ include "py_log_demo.selectorLabels" . | indent 8 }}
  strategy: {}
  template:
    metadata:
      labels:
{{ include "py_log_demo.selectorLabels" . | indent 8 }}
      annotations:
{{ include "py_log_demo.annotations" . | indent 8 }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: "main"
        ports:
{{ toYaml (.Values.container_ports) | indent 8 }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        imagePullPolicy: Never
