---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  {{- include "py_log_demo.labels" . | nindent 4 }}
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
    {{- include "py_log_demo.selectorLabels" . | nindent 8 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "py_log_demo.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "py_log_demo.annotations" . | nindent 8 }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: "main"
        ports:
          {{- toYaml (.Values.container_ports) | nindent 8 }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- with .Values.env }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        dnsPolicy: {{ .Values.dns.policy | default "Default" }}
        {{- with .Values.dns.config }}
        dnsConfig:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- include "py_log_demo.resources" . | nindent 8 }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
