---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.app }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "py_log_demo.selectorLabels" . | nindent 6 }}
