{{- with .Values.gh_packages_token }}
apiVersion: v1
kind: Secret
metadata:
  name: image-secret
  labels:
    {{- include "py_log_demo.labels" $ | nindent 4 }}
  annotations:
    {{- include "py_log_demo.annotations" $ | nindent 4 }}
data:
  .dockerconfigjson: {{ . }}
{{- end}}
