---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "py_log_demo.labels" . | nindent 4 }}
  annotations:
    {{- include "py_log_demo.annotations" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
    {{- with .Values.service_ports }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "py_log_demo.selectorLabels" . | nindent 4 }}
  type: ClusterIP
