---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "py_log_demo.labels" . | indent 4 }}
spec:
  ports:
{{ toYaml (.Values.service_ports) | indent 4 }}
  selector:
{{ include "py_log_demo.selectorLabels" . | indent 4 }}
  type: ClusterIP
