---
app: demo-app-python
namespace: demo-apps
image: local/python-logs-demo-app:v1.0.0
type: python

container_ports:
  - containerPort: 5000
    name: "main"

service_ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: "main"

resources:
  requests:
    memory: "24Mi"
    cpu: "64m"
  limits:
    memory: "24Mi"
    cpu: "64m"
