---
# yamllint disable rule:line-length
name: main

on:
  push:
    paths-ignore:
      - "demo-services/**" # Ignore demo-services as they have their own workflow
      - ".github/**"

env:
  TERRAFORM_VERSION: 1.8.1
  TERRAFORM_DOCS_VERSION: 0.16.0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${TERRAFORM_VERSION}
      - name: Install yamllint
        run: pip install yamllint
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Install terrafrom dependencies
        run: |
          # Install terraform docs
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v${TERRAFORM_DOCS_VERSION}/terraform-docs-v${TERRAFORM_DOCS_VERSION}-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mv terraform-docs $HOME/.local/bin

          # Add local executable to PATH
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-8
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Run pre-commit
        run: pre-commit run --all-files
