---
# yamllint disable rule:line-length
name: main

on:
  push:
    paths-ignore:
      - "demo-services/**" # Ignore demo-services as they have their own workflow

env:
  TERRAFORM_VERSION: 1.3.1
  TERRAFORM_DOCS_VERSION: 0.16.0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yamllint
        run: pip install yamllint
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Install terrafrom dependencies
        run: |
          # Install terraform
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install -y terraform=${TERRAFORM_VERSION}

          # Install terraform docs
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v${TERRAFORM_DOCS_VERSION}/terraform-docs-v${TERRAFORM_DOCS_VERSION}-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mv terraform-docs $HOME/.local/bin

          # Add local executable to PATH
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-8
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Run pre-commit
        run: pre-commit run --all-files
