---
# yamllint disable rule:line-length
name: python-app-ci

on:
  pull_request:
    paths:
      - "demo-services/python-app/**"

jobs:
  test:
    strategy:
      matrix:
        include:
          - check_name: black
            script: |
              pip install black
              black--check --no-color --exclude deployment/* .
            os: "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Running ${{ matrix.command }}
        run: |
          echo ${{ matrix.script }} > script.sh
          cat script.sh
