---
# yamllint disable rule:line-length
name: python-app-ci

on:
  pull_request:
    paths:
      - "demo-services/python-app/**"

jobs:
  test:
    strategy:
      matrix:
        # Generate jobs for running tests
        include:
          - check_name: black
            working_directory: "demo-services/python-app/"
            script: |
              pip install black
              black --check --no-color --exclude "deployment/*" .
            os: "ubuntu-latest"
          - check_name: yamllint
            working_directory: "demo-services/python-app/"
            script: |
              echo "############## Run lint for ###########"
              yamllint --list-files ./
              echo "#######################################"
              yamllint --no-warnings ./
            os: "ubuntu-latest"
          # - check_name: kubeconform
          #   working_directory: "demo-services/python-app/"
          #   script: |
          #     pip install black
          #     black --check --no-color --exclude "deployment/*" .
          #   os: "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Running ${{ matrix.check_name }}
        working-directory: ${{ matrix.working_directory }}
        run: |
          echo '${{ matrix.script }}' > script.sh
          bash -c "$(cat script.sh)"
